name = "temperature"
description = "Micro:bit v2 internal temperature sensor example"
version = "0.1.0"
authors = ["Jorlly Collado <jorlly@collado.ch>"]
maintainers = ["Jorlly Collado <jorlly@collado.ch>"]
maintainers-logins = ["jorlly-collado-castro"]
licenses = "GPL-3.0-only"
project-files = ["temperature.gpr"]
tags = ["microbit", "bare-metal", "temperature"]

[[depends-on]]
microbit_v2 = "*"

[[pins]]
microbit_v2 = { path='../..' }
