/* Configuration for microbit_v2 generated by Alire */
#ifndef MICROBIT_V2_CONFIG_H
#define MICROBIT_V2_CONFIG_H

#define CRATE_VERSION "0.1.0"
#define CRATE_NAME "microbit_v2"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "arch"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
