pragma Style_Checks (Off);

--  Copyright (c) 2010 - 2020, Nordic Semiconductor ASA All rights reserved.
--
--  Redistribution and use in source and binary forms, with or without
--  modification, are permitted provided that the following conditions are met:
--
--  1. Redistributions of source code must retain the above copyright notice, this
--  list of conditions and the following disclaimer.
--
--  2. Redistributions in binary form must reproduce the above copyright
--  notice, this list of conditions and the following disclaimer in the
--  documentation and/or other materials provided with the distribution.
--
--  3. Neither the name of Nordic Semiconductor ASA nor the names of its
--  contributors may be used to endorse or promote products derived from this
--  software without specific prior written permission.
--
--  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
--  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
--  IMPLIED WARRANTIES OF MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE
--  ARE DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
--  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
--  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
--  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
--  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
--  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
--  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
--  POSSIBILITY OF SUCH DAMAGE.
--

--  This spec has been automatically generated from nrf52833.svd

pragma Restrictions (No_Elaboration_Code);

with NRF52833_SVD;
with System;

package NRF52833_SVD.EGU is
   pragma Preelaborate;

   ---------------
   -- Registers --
   ---------------

   --  Trigger n for triggering the corresponding TRIGGERED[n] event
   type TASKS_TRIGGER_TASKS_TRIGGER_Field is
     (--  Reset value for the field
      TASKS_TRIGGER_TASKS_TRIGGER_Field_Reset,
      --  Trigger task
      Trigger)
     with Size => 1;
   for TASKS_TRIGGER_TASKS_TRIGGER_Field use
     (TASKS_TRIGGER_TASKS_TRIGGER_Field_Reset => 0,
      Trigger => 1);

   --  Description collection: Trigger n for triggering the corresponding
   --  TRIGGERED[n] event
   type TASKS_TRIGGER_Register is record
      --  Write-only. Trigger n for triggering the corresponding TRIGGERED[n]
      --  event
      TASKS_TRIGGER : TASKS_TRIGGER_TASKS_TRIGGER_Field :=
                       TASKS_TRIGGER_TASKS_TRIGGER_Field_Reset;
      --  unspecified
      Reserved_1_31 : NRF52833_SVD.UInt31 := 16#0#;
   end record
     with Volatile_Full_Access, Object_Size => 32,
          Bit_Order => System.Low_Order_First;

   for TASKS_TRIGGER_Register use record
      TASKS_TRIGGER at 0 range 0 .. 0;
      Reserved_1_31 at 0 range 1 .. 31;
   end record;

   --  Description collection: Trigger n for triggering the corresponding
   --  TRIGGERED[n] event
   type TASKS_TRIGGER_Registers is array (0 .. 15) of TASKS_TRIGGER_Register;

   --  Event number n generated by triggering the corresponding TRIGGER[n] task
   type EVENTS_TRIGGERED_EVENTS_TRIGGERED_Field is
     (--  Event not generated
      NotGenerated,
      --  Event generated
      Generated)
     with Size => 1;
   for EVENTS_TRIGGERED_EVENTS_TRIGGERED_Field use
     (NotGenerated => 0,
      Generated => 1);

   --  Description collection: Event number n generated by triggering the
   --  corresponding TRIGGER[n] task
   type EVENTS_TRIGGERED_Register is record
      --  Event number n generated by triggering the corresponding TRIGGER[n]
      --  task
      EVENTS_TRIGGERED : EVENTS_TRIGGERED_EVENTS_TRIGGERED_Field :=
                          NRF52833_SVD.EGU.NotGenerated;
      --  unspecified
      Reserved_1_31    : NRF52833_SVD.UInt31 := 16#0#;
   end record
     with Volatile_Full_Access, Object_Size => 32,
          Bit_Order => System.Low_Order_First;

   for EVENTS_TRIGGERED_Register use record
      EVENTS_TRIGGERED at 0 range 0 .. 0;
      Reserved_1_31    at 0 range 1 .. 31;
   end record;

   --  Description collection: Event number n generated by triggering the
   --  corresponding TRIGGER[n] task
   type EVENTS_TRIGGERED_Registers is array (0 .. 15)
     of EVENTS_TRIGGERED_Register;

   --  Enable or disable interrupt for event TRIGGERED[0]
   type INTEN_TRIGGERED0_Field is
     (--  Disable
      Disabled,
      --  Enable
      Enabled)
     with Size => 1;
   for INTEN_TRIGGERED0_Field use
     (Disabled => 0,
      Enabled => 1);

   --  INTEN_TRIGGERED array
   type INTEN_TRIGGERED_Field_Array is array (0 .. 15)
     of INTEN_TRIGGERED0_Field
     with Component_Size => 1, Size => 16;

   --  Type definition for INTEN_TRIGGERED
   type INTEN_TRIGGERED_Field
     (As_Array : Boolean := False)
   is record
      case As_Array is
         when False =>
            --  TRIGGERED as a value
            Val : NRF52833_SVD.UInt16;
         when True =>
            --  TRIGGERED as an array
            Arr : INTEN_TRIGGERED_Field_Array;
      end case;
   end record
     with Unchecked_Union, Size => 16;

   for INTEN_TRIGGERED_Field use record
      Val at 0 range 0 .. 15;
      Arr at 0 range 0 .. 15;
   end record;

   --  Enable or disable interrupt
   type INTEN_Register is record
      --  Enable or disable interrupt for event TRIGGERED[0]
      TRIGGERED      : INTEN_TRIGGERED_Field :=
                        (As_Array => False, Val => 16#0#);
      --  unspecified
      Reserved_16_31 : NRF52833_SVD.UInt16 := 16#0#;
   end record
     with Volatile_Full_Access, Object_Size => 32,
          Bit_Order => System.Low_Order_First;

   for INTEN_Register use record
      TRIGGERED      at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   --  Write '1' to enable interrupt for event TRIGGERED[0]
   type INTENSET_TRIGGERED0_Field is
     (--  Read: Disabled
      Disabled,
      --  Read: Enabled
      Enabled)
     with Size => 1;
   for INTENSET_TRIGGERED0_Field use
     (Disabled => 0,
      Enabled => 1);

   --  Write '1' to enable interrupt for event TRIGGERED[0]
   type INTENSET_TRIGGERED0_Field_1 is
     (--  Reset value for the field
      INTENSET_TRIGGERED0_Field_Reset,
      --  Enable
      Set)
     with Size => 1;
   for INTENSET_TRIGGERED0_Field_1 use
     (INTENSET_TRIGGERED0_Field_Reset => 0,
      Set => 1);

   --  INTENSET_TRIGGERED array
   type INTENSET_TRIGGERED_Field_Array is array (0 .. 15)
     of INTENSET_TRIGGERED0_Field_1
     with Component_Size => 1, Size => 16;

   --  Type definition for INTENSET_TRIGGERED
   type INTENSET_TRIGGERED_Field
     (As_Array : Boolean := False)
   is record
      case As_Array is
         when False =>
            --  TRIGGERED as a value
            Val : NRF52833_SVD.UInt16;
         when True =>
            --  TRIGGERED as an array
            Arr : INTENSET_TRIGGERED_Field_Array;
      end case;
   end record
     with Unchecked_Union, Size => 16;

   for INTENSET_TRIGGERED_Field use record
      Val at 0 range 0 .. 15;
      Arr at 0 range 0 .. 15;
   end record;

   --  Enable interrupt
   type INTENSET_Register is record
      --  Write '1' to enable interrupt for event TRIGGERED[0]
      TRIGGERED      : INTENSET_TRIGGERED_Field :=
                        (As_Array => False, Val => 16#0#);
      --  unspecified
      Reserved_16_31 : NRF52833_SVD.UInt16 := 16#0#;
   end record
     with Volatile_Full_Access, Object_Size => 32,
          Bit_Order => System.Low_Order_First;

   for INTENSET_Register use record
      TRIGGERED      at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   --  Write '1' to disable interrupt for event TRIGGERED[0]
   type INTENCLR_TRIGGERED0_Field is
     (--  Read: Disabled
      Disabled,
      --  Read: Enabled
      Enabled)
     with Size => 1;
   for INTENCLR_TRIGGERED0_Field use
     (Disabled => 0,
      Enabled => 1);

   --  Write '1' to disable interrupt for event TRIGGERED[0]
   type INTENCLR_TRIGGERED0_Field_1 is
     (--  Reset value for the field
      INTENCLR_TRIGGERED0_Field_Reset,
      --  Disable
      Clear)
     with Size => 1;
   for INTENCLR_TRIGGERED0_Field_1 use
     (INTENCLR_TRIGGERED0_Field_Reset => 0,
      Clear => 1);

   --  INTENCLR_TRIGGERED array
   type INTENCLR_TRIGGERED_Field_Array is array (0 .. 15)
     of INTENCLR_TRIGGERED0_Field_1
     with Component_Size => 1, Size => 16;

   --  Type definition for INTENCLR_TRIGGERED
   type INTENCLR_TRIGGERED_Field
     (As_Array : Boolean := False)
   is record
      case As_Array is
         when False =>
            --  TRIGGERED as a value
            Val : NRF52833_SVD.UInt16;
         when True =>
            --  TRIGGERED as an array
            Arr : INTENCLR_TRIGGERED_Field_Array;
      end case;
   end record
     with Unchecked_Union, Size => 16;

   for INTENCLR_TRIGGERED_Field use record
      Val at 0 range 0 .. 15;
      Arr at 0 range 0 .. 15;
   end record;

   --  Disable interrupt
   type INTENCLR_Register is record
      --  Write '1' to disable interrupt for event TRIGGERED[0]
      TRIGGERED      : INTENCLR_TRIGGERED_Field :=
                        (As_Array => False, Val => 16#0#);
      --  unspecified
      Reserved_16_31 : NRF52833_SVD.UInt16 := 16#0#;
   end record
     with Volatile_Full_Access, Object_Size => 32,
          Bit_Order => System.Low_Order_First;

   for INTENCLR_Register use record
      TRIGGERED      at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   -----------------
   -- Peripherals --
   -----------------

   --  Event generator unit 0
   type EGU_Peripheral is record
      --  Description collection: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER    : aliased TASKS_TRIGGER_Registers;
      --  Description collection: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED : aliased EVENTS_TRIGGERED_Registers;
      --  Enable or disable interrupt
      INTEN            : aliased INTEN_Register;
      --  Enable interrupt
      INTENSET         : aliased INTENSET_Register;
      --  Disable interrupt
      INTENCLR         : aliased INTENCLR_Register;
   end record
     with Volatile;

   for EGU_Peripheral use record
      TASKS_TRIGGER    at 16#0# range 0 .. 511;
      EVENTS_TRIGGERED at 16#100# range 0 .. 511;
      INTEN            at 16#300# range 0 .. 31;
      INTENSET         at 16#304# range 0 .. 31;
      INTENCLR         at 16#308# range 0 .. 31;
   end record;

   --  Event generator unit 0
   EGU0_Periph : aliased EGU_Peripheral
     with Import, Address => EGU0_Base;

   --  Event generator unit 1
   EGU1_Periph : aliased EGU_Peripheral
     with Import, Address => EGU1_Base;

   --  Event generator unit 2
   EGU2_Periph : aliased EGU_Peripheral
     with Import, Address => EGU2_Base;

   --  Event generator unit 3
   EGU3_Periph : aliased EGU_Peripheral
     with Import, Address => EGU3_Base;

   --  Event generator unit 4
   EGU4_Periph : aliased EGU_Peripheral
     with Import, Address => EGU4_Base;

   --  Event generator unit 5
   EGU5_Periph : aliased EGU_Peripheral
     with Import, Address => EGU5_Base;

end NRF52833_SVD.EGU;
