pragma SPARK_Mode (On);
package Microbit.Display.Font is

   type Character_Matrix is array (0 .. 4, 0 .. 4) of Boolean;
   type Font_Array is array (Character range ' ' .. '~') of Character_Matrix;

   Data : constant Font_Array :=
     (
      ' ' =>
        ((False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False)),
      '!' =>
        ((False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, False, False, False, False),
         (False, True, False, False, False)),
      '"' =>
        ((False, True, False, True, False),
         (False, True, False, True, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False)),
      '#' =>
        ((False, True, False, True, False),
         (True, True, True, True, True),
         (False, True, False, True, False),
         (True, True, True, True, True),
         (False, True, False, True, False)),
      '$' =>
        ((False, True, True, True, False),
         (True, True, False, False, True),
         (False, True, True, True, False),
         (True, False, False, True, True),
         (False, True, True, True, False)),
      '%' =>
        ((True, True, False, False, True),
         (True, False, False, True, False),
         (False, False, True, False, False),
         (False, True, False, False, True),
         (True, False, False, True, True)),
      '&' =>
        ((False, True, True, False, False),
         (True, False, False, True, False),
         (False, True, True, False, False),
         (True, False, False, True, False),
         (False, True, True, False, True)),
      ''' =>
        ((False, True, False, False, False),
         (False, True, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False)),
      '(' =>
        ((False, False, True, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, False, True, False, False)),
      ')' =>
        ((False, True, False, False, False),
         (False, False, True, False, False),
         (False, False, True, False, False),
         (False, False, True, False, False),
         (False, True, False, False, False)),
      '*' =>
        ((False, False, False, False, False),
         (False, True, False, True, False),
         (False, False, True, False, False),
         (False, True, False, True, False),
         (False, False, False, False, False)),
      '+' =>
        ((False, False, False, False, False),
         (False, False, True, False, False),
         (False, True, True, True, False),
         (False, False, True, False, False),
         (False, False, False, False, False)),
      ',' =>
        ((False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, True, False, False),
         (False, True, False, False, False)),
      '-' =>
        ((False, False, False, False, False),
         (False, False, False, False, False),
         (False, True, True, True, False),
         (False, False, False, False, False),
         (False, False, False, False, False)),
      '.' =>
        ((False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (False, True, False, False, False),
         (False, False, False, False, False)),
      '/' =>
        ((False, False, False, False, True),
         (False, False, False, True, False),
         (False, False, True, False, False),
         (False, True, False, False, False),
         (True, False, False, False, False)),
      '0' =>
        ((False, True, True, False, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (False, True, True, False, False)),
      '1' =>
        ((False, False, True, False, False),
         (False, True, True, False, False),
         (False, False, True, False, False),
         (False, False, True, False, False),
         (False, True, True, True, False)),
      '2' =>
        ((True, True, True, False, False),
         (False, False, False, True, False),
         (False, True, True, False, False),
         (True, False, False, False, False),
         (True, True, True, True, False)),
      '3' =>
        ((True, True, True, True, False),
         (False, False, False, True, False),
         (False, False, True, False, False),
         (True, False, False, True, False),
         (False, True, True, False, False)),
      '4' =>
        ((False, False, True, True, False),
         (False, True, False, True, False),
         (True, False, False, True, False),
         (True, True, True, True, True),
         (False, False, False, True, False)),
      '5' =>
        ((True, True, True, True, True),
         (True, False, False, False, False),
         (True, True, True, True, False),
         (False, False, False, False, True),
         (True, True, True, True, False)),
      '6' =>
        ((False, False, False, True, False),
         (False, False, True, False, False),
         (False, True, True, True, False),
         (True, False, False, False, True),
         (False, True, True, True, False)),
      '7' =>
        ((True, True, True, True, True),
         (False, False, False, True, False),
         (False, False, True, False, False),
         (False, True, False, False, False),
         (True, False, False, False, False)),
      '8' =>
        ((False, True, True, True, False),
         (True, False, False, False, True),
         (False, True, True, True, False),
         (True, False, False, False, True),
         (False, True, True, True, False)),
      '9' =>
        ((False, True, True, True, False),
         (True, False, False, False, True),
         (False, True, True, True, False),
         (False, False, True, False, False),
         (False, True, False, False, False)),
      ':' =>
        ((False, False, False, False, False),
         (False, True, False, False, False),
         (False, False, False, False, False),
         (False, True, False, False, False),
         (False, False, False, False, False)),
      ';' =>
        ((False, False, False, False, False),
         (False, False, True, False, False),
         (False, False, False, False, False),
         (False, False, True, False, False),
         (False, True, False, False, False)),
      '<' =>
        ((False, False, False, True, False),
         (False, False, True, False, False),
         (False, True, False, False, False),
         (False, False, True, False, False),
         (False, False, False, True, False)),
      '=' =>
        ((False, False, False, False, False),
         (False, True, True, True, False),
         (False, False, False, False, False),
         (False, True, True, True, False),
         (False, False, False, False, False)),
      '>' =>
        ((False, True, False, False, False),
         (False, False, True, False, False),
         (False, False, False, True, False),
         (False, False, True, False, False),
         (False, True, False, False, False)),
      '?' =>
        ((False, True, True, True, False),
         (True, False, False, False, True),
         (False, False, True, True, False),
         (False, False, False, False, False),
         (False, False, True, False, False)),
      '@' =>
        ((False, True, True, True, False),
         (True, False, False, False, True),
         (True, False, True, False, True),
         (True, False, False, True, True),
         (False, True, True, False, False)),
      'A' =>
        ((False, True, True, False, False),
         (True, False, False, True, False),
         (True, True, True, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False)),
      'B' =>
        ((True, True, True, False, False),
         (True, False, False, True, False),
         (True, True, True, False, False),
         (True, False, False, True, False),
         (True, True, True, False, False)),
      'C' =>
        ((False, True, True, True, False),
         (True, False, False, False, False),
         (True, False, False, False, False),
         (True, False, False, False, False),
         (False, True, True, True, False)),
      'D' =>
        ((True, True, True, False, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (True, True, True, False, False)),
      'E' =>
        ((True, True, True, True, False),
         (True, False, False, False, False),
         (True, True, True, False, False),
         (True, False, False, False, False),
         (True, True, True, True, False)),
      'F' =>
        ((True, True, True, True, False),
         (True, False, False, False, False),
         (True, True, True, False, False),
         (True, False, False, False, False),
         (True, False, False, False, False)),
      'G' =>
        ((False, True, True, True, False),
         (True, False, False, False, False),
         (True, False, False, True, True),
         (True, False, False, False, True),
         (False, True, True, True, False)),
      'H' =>
        ((True, False, False, True, False),
         (True, False, False, True, False),
         (True, True, True, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False)),
      'I' =>
        ((True, True, True, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (True, True, True, False, False)),
      'J' =>
        ((True, True, True, True, True),
         (False, False, False, True, False),
         (False, False, False, True, False),
         (True, False, False, True, False),
         (False, True, True, False, False)),
      'K' =>
        ((True, False, False, True, False),
         (True, False, True, False, False),
         (True, True, False, False, False),
         (True, False, True, False, False),
         (True, False, False, True, False)),
      'L' =>
        ((True, False, False, False, False),
         (True, False, False, False, False),
         (True, False, False, False, False),
         (True, False, False, False, False),
         (True, True, True, True, False)),
      'M' =>
        ((True, False, False, False, True),
         (True, True, False, True, True),
         (True, False, True, False, True),
         (True, False, False, False, True),
         (True, False, False, False, True)),
      'N' =>
        ((True, False, False, False, True),
         (True, True, False, False, True),
         (True, False, True, False, True),
         (True, False, False, True, True),
         (True, False, False, False, True)),
      'O' =>
        ((False, True, True, False, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (False, True, True, False, False)),
      'P' =>
        ((True, True, True, False, False),
         (True, False, False, True, False),
         (True, True, True, False, False),
         (True, False, False, False, False),
         (True, False, False, False, False)),
      'Q' =>
        ((False, True, True, False, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (False, True, True, False, False),
         (False, False, True, True, False)),
      'R' =>
        ((True, True, True, False, False),
         (True, False, False, True, False),
         (True, True, True, False, False),
         (True, False, False, True, False),
         (True, False, False, False, True)),
      'S' =>
        ((False, True, True, True, False),
         (True, False, False, False, False),
         (False, True, True, False, False),
         (False, False, False, True, False),
         (True, True, True, False, False)),
      'T' =>
        ((True, True, True, True, True),
         (False, False, True, False, False),
         (False, False, True, False, False),
         (False, False, True, False, False),
         (False, False, True, False, False)),
      'U' =>
        ((True, False, False, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (False, True, True, False, False)),
      'V' =>
        ((True, False, False, False, True),
         (True, False, False, False, True),
         (True, False, False, False, True),
         (False, True, False, True, False),
         (False, False, True, False, False)),
      'W' =>
        ((True, False, False, False, True),
         (True, False, False, False, True),
         (True, False, True, False, True),
         (True, True, False, True, True),
         (True, False, False, False, True)),
      'X' =>
        ((True, False, False, True, False),
         (True, False, False, True, False),
         (False, True, True, False, False),
         (True, False, False, True, False),
         (True, False, False, True, False)),
      'Y' =>
        ((True, False, False, False, True),
         (False, True, False, True, False),
         (False, False, True, False, False),
         (False, False, True, False, False),
         (False, False, True, False, False)),
      'Z' =>
        ((True, True, True, True, False),
         (False, False, True, False, False),
         (False, True, False, False, False),
         (True, False, False, False, False),
         (True, True, True, True, False)),
      '[' =>
        ((False, True, True, True, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, True, True, False)),
      '\' =>
        ((True, False, False, False, False),
         (False, True, False, False, False),
         (False, False, True, False, False),
         (False, False, False, True, False),
         (False, False, False, False, True)),
      ']' =>
        ((False, True, True, True, False),
         (False, False, False, True, False),
         (False, False, False, True, False),
         (False, False, False, True, False),
         (False, True, True, True, False)),
      '^' =>
        ((False, False, True, False, False),
         (False, True, False, True, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False)),
      '_' =>
        ((False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (True, True, True, True, True)),
      '`' =>
        ((False, True, False, False, False),
         (False, False, True, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False),
         (False, False, False, False, False)),
      'a' =>
        ((False, False, False, False, False),
         (False, True, True, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (False, True, True, True, True)),
      'b' =>
        ((True, False, False, False, False),
         (True, False, False, False, False),
         (True, True, True, False, False),
         (True, False, False, True, False),
         (True, True, True, False, False)),
      'c' =>
        ((False, False, False, False, False),
         (False, True, True, True, False),
         (True, False, False, False, False),
         (True, False, False, False, False),
         (False, True, True, True, False)),
      'd' =>
        ((False, False, False, True, False),
         (False, False, False, True, False),
         (False, True, True, True, False),
         (True, False, False, True, False),
         (False, True, True, True, False)),
      'e' =>
        ((False, True, True, False, False),
         (True, False, False, True, False),
         (True, True, True, False, False),
         (True, False, False, False, False),
         (False, True, True, True, False)),
      'f' =>
        ((False, False, True, True, False),
         (False, True, False, False, False),
         (True, True, True, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False)),
      'g' =>
        ((False, True, True, True, False),
         (True, False, False, True, False),
         (False, True, True, True, False),
         (False, False, False, True, False),
         (False, True, True, False, False)),
      'h' =>
        ((True, False, False, False, False),
         (True, False, False, False, False),
         (True, True, True, False, False),
         (True, False, False, True, False),
         (True, False, False, True, False)),
      'i' =>
        ((False, True, False, False, False),
         (False, False, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False)),
      'j' =>
        ((False, False, False, True, False),
         (False, False, False, False, False),
         (False, False, False, True, False),
         (False, False, False, True, False),
         (False, True, True, False, False)),
      'k' =>
        ((True, False, False, False, False),
         (True, False, True, False, False),
         (True, True, False, False, False),
         (True, False, True, False, False),
         (True, False, False, True, False)),
      'l' =>
        ((False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, False, True, True, False)),
      'm' =>
        ((False, False, False, False, False),
         (True, True, False, True, True),
         (True, False, True, False, True),
         (True, False, False, False, True),
         (True, False, False, False, True)),
      'n' =>
        ((False, False, False, False, False),
         (True, True, True, False, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False)),
      'o' =>
        ((False, False, False, False, False),
         (False, True, True, False, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (False, True, True, False, False)),
      'p' =>
        ((False, False, False, False, False),
         (True, True, True, False, False),
         (True, False, False, True, False),
         (True, True, True, False, False),
         (True, False, False, False, False)),
      'q' =>
        ((False, False, False, False, False),
         (False, True, True, True, False),
         (True, False, False, True, False),
         (False, True, True, True, False),
         (False, False, False, True, False)),
      'r' =>
        ((False, False, False, False, False),
         (False, True, True, True, False),
         (True, False, False, False, False),
         (True, False, False, False, False),
         (True, False, False, False, False)),
      's' =>
        ((False, False, False, False, False),
         (False, False, True, True, False),
         (False, True, False, False, False),
         (False, False, True, False, False),
         (True, True, False, False, False)),
      't' =>
        ((False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, True, True, False),
         (False, True, False, False, False),
         (False, False, True, True, True)),
      'u' =>
        ((False, False, False, False, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (True, False, False, True, False),
         (False, True, True, True, True)),
      'v' =>
        ((False, False, False, False, False),
         (True, False, False, False, True),
         (True, False, False, False, True),
         (False, True, False, True, False),
         (False, False, True, False, False)),
      'w' =>
        ((False, False, False, False, False),
         (True, False, False, False, True),
         (True, False, False, False, True),
         (True, False, True, False, True),
         (True, True, False, True, True)),
      'x' =>
        ((False, False, False, False, False),
         (True, False, False, True, False),
         (False, True, True, False, False),
         (False, True, True, False, False),
         (True, False, False, True, False)),
      'y' =>
        ((False, False, False, False, False),
         (True, False, False, False, True),
         (False, True, False, True, False),
         (False, False, True, False, False),
         (True, True, False, False, False)),
      'z' =>
        ((False, False, False, False, False),
         (True, True, True, True, False),
         (False, False, True, False, False),
         (False, True, False, False, False),
         (True, True, True, True, False)),
      '{' =>
        ((False, False, True, True, False),
         (False, False, True, False, False),
         (False, True, True, False, False),
         (False, False, True, False, False),
         (False, False, True, True, False)),
      '|' =>
        ((False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False),
         (False, True, False, False, False)),
      '}' =>
        ((True, True, False, False, False),
         (False, True, False, False, False),
         (False, True, True, False, False),
         (False, True, False, False, False),
         (True, True, False, False, False)),
      '~' =>
        ((False, False, False, False, False),
         (False, False, False, False, False),
         (False, True, True, False, False),
         (False, False, False, True, True),
         (False, False, False, False, False))
     );

end Microbit.Display.Font;
